[build]
  command = "npm install"
  functions = "functions"
  publish = "proyecto/frontend"

[dev]
  command = "npm run dev --prefix proyecto/backend"
  port = 4000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
